// ════════════════════════════════════════════════════════════════════
// ★★★★★ 全站文字设置区（中文）★★★★★
// 原版 HTML 里这块叫 window.DOWNLOAD_STATION_TEXT —— 全站文字就集中在
// 这一个地方。本文件放在项目根目录，打开就能改。
//
// 【日常改文字 = 只改这个文件】建议只改引号里的文字，不要动左边的 key
// （key 是页面找文字的“编号”，例如 home.title，改错就找不到文字了）。
// 改完保存：npm run dev 下浏览器自动刷新；发布前跑 npm run build
// 或 npm run build:single。
//
// 英文站文字在 src/gallery/Strings/en-US/Resources.ts（和这里一一对应，
// 中文站改了顺手同步英文站；只维护中文站可不管它）。
// 软件数据（软件名/简介/下载链接不在这里）→ 根目录「软件数据」文件夹。
//
// key 速查：app.*=站名/版权/版本号；home.*=首页标题区+
//             「教学辅助」分类顶部的外链推荐卡（home.iwb-card-*）；
// filter.*=筛选条；detail.*=详情页；text.*=通用按钮/设置页；
// about.*=设置页“关于”区（*-url 是链接地址；QQ 群入口=about.qq-group(+url)）。
// welcome.*=欢迎弹窗（进入网站时弹出；仓库/作者/QQ 群链接复用 about.*-url 键；
//           相关文章=welcome.article(+url)，投喂作者=about.reward(+url)）。
// search.*=全站搜索（Ctrl+K 面板：描述文字、分组名、页面条目、快捷键提示；
//           以及工具页那句“按 Ctrl + K 搜索”的提示）。
// ════════════════════════════════════════════════════════════════════
export default {
      "app.title": "电教委员常用软件下载站",
      "text.back": "返回",
      "text.copy": "复制",
      "text.more": "更多",
      "text.navigation-menu": "导航菜单",
      "text.search": "搜索",
      "text.select": "选择",
      "text.select-all": "全选",
      "text.default-navigation-transition-info": "默认 (DefaultNavigationTransitionInfo)",
      "text.entrance-navigation-transition-info": "进入 (EntranceNavigationTransitionInfo)",
      "text.drill-in-navigation-transition-info": "钻取 (DrillInNavigationTransitionInfo)",
      "text.suppress-navigation-transition-info": "无动画 (SuppressNavigationTransitionInfo)",
      "text.slide-navigation-transition-info-from-right": "滑动 (SlideNavigationTransitionInfo, Effect = FromRight)",
      "text.slide-navigation-transition-info-from-left": "滑动 (SlideNavigationTransitionInfo, Effect = FromLeft)",
      "text.common-navigation-transition-info": "通用 (CommonNavigationTransitionInfo)",
      "text.continuum-navigation-transition-info": "连续 (ContinuumNavigationTransitionInfo)",
      "text.about-copyright": "© {year} {author}。{rights}",
      "theme-toggle": "切换主题",
      "favorite-toggle": "收藏",
      "text.about": "关于",
      "text.acrylic": "Acrylic",
      "text.all-rights-reserved": "",
      "text.animation-style-when-switching-pages": "切换页面时的动画样式",
      "text.appearance": "外观",
      "text.choose-the-app-background-material": "选择应用背景材质",
      "text.choose-your-app-color-mode": "选择应用颜色模式",
      "text.holiday-skin": "节日皮肤",
      "text.holiday-skin-desc": "节日档期内自动换上应景横幅与主题色（中秋 / 国庆）；档期外也可以手动打开。",
      "text.on": "开启",
      "text.off": "关闭",
      "text.dark": "深色",
      "text.discord-group": "Discord 群组",
      "text.left": "左侧",
      "text.light": "浅色",
      "text.material": "材质",
      "text.mica": "Mica",
      "text.navigation-pane-position": "导航窗格位置",
      "text.open-code-repository": "打开代码仓库",
      "about.author-home": "作者首页",
      "about.author-home-url": "https://space.bilibili.com/1274920807",
      "about.echo-cave": "回声洞",
      "about.echo-cave-url": "https://www.bilibili.com/video/BV1GJ411x7h7/",
      // QQ 群入口（「关于」区 + 首页欢迎弹窗都用这两条）
      "about.qq-group": "加入 QQ 群",
      "about.qq-group-url": "https://qm.qq.com/q/wByO7XG8Wk",
      "about.reward": "投喂作者",
      "about.reward-url": "https://ifdian.net/a/TinyNickCSHub",
      "about.repository-url": "https://github.com/c1201y/ClassSoftwareHub",
      // 「关于」里的 UI 内核链接：本站界面用的上游组件库 WinUIonWeb（致敬原作者）
      "about.ui-kernel": "UI 内核（WinUIonWeb）",
      "about.ui-kernel-url": "https://github.com/Furry-Xiyi/WinUIonWeb",
      // 「回声洞」设置页展开项（数据在根目录 回声洞/messages/，一条一个文件）
      // subtitle 仍被站内页 /echo-cave 用着，留着
      // ⛔ 展开区里只显示字条本身，卡面不许再有任何状态字（2026-10-03 Nick 指定）
      "echo-cave.title": "回声洞",
      "echo-cave.subtitle": "收集 QQ 群里那些让人笑出声的沙雕发言，点一下换一条。",
      "echo-cave.description": "请点击这里收看 ClassSoftwareHub 群友的逆天发言！",
      "echo-cave.placeholder": "点击此处可以查看 ClassSoftwareHub 群友逆天发言",
      "echo-cave.empty": "还没有任何发言，点「投稿」写第一条吧～",
      "echo-cave.submit": "投稿沙雕发言",
      "echo-cave.submit-note": "会在 GitHub 上打开投稿目录，新建一个 .json 草稿提交，审核通过后才会收进回声洞。",
      "echo-cave.count": "共 {total} 条",
      // 投稿小面板（设置页回声洞展开区右侧按钮）
      "echo-cave.submit-short": "投稿",
      "echo-cave.submit-title": "投稿到回声洞",
      "echo-cave.submit-placeholder": "写一句让人笑出声的话",
      "echo-cave.submit-send": "提交",
      "echo-cave.submit-sending": "投稿中…",
      "echo-cave.submit-empty": "先写一句话再投稿吧。",
      "echo-cave.submit-failed": "连不上投稿服务，可以改用 GitHub 网页投稿。",
      "echo-cave.submit-ok": "投稿成功！审核通过后会出现在回声洞里。",
      "echo-cave.submit-fallback": "改用 GitHub 网页投稿",
      "text.page-transition": "页面过渡",
      "text.qq-group": "QQ 群组",
      "text.select-the-navigation-bar-position": "选择导航栏位置",
      "text.settings": "设置",
      "text.theme": "主题",
      "text.top": "顶部",
      "text.use-system-setting": "使用系统设置",
      "nav.home": "首页",
      "nav.feedback": "反馈中心",
      "home.title": "ClassSoftwareHub",
      "home.subtitle": "欢迎使用下载站【v2.3.4 - Tangram】，欢迎各位添砖加瓦，感谢 @Bilibili 椰汁cyan 提供网站的搭建！",
      "home.download-template": "下载软件添加模板【开发者】",
      "home.download-template-tip": "共创！添加软件使用的模板",
      "home.download-template-filename": "模板.json",
      // ★首页「教学辅助」分类顶部的外链推荐卡（Awesome IWB）
      //   想换推荐的网站/改文案：只动下面这 4 个 key。
      //   url 填完整网址（https:// 开头）；把 title 和 desc 都留空("")这张卡就不显示。
      "home.iwb-card-title": "想找更多教学软件？去 Awesome IWB 逛逛",
      "home.iwb-card-desc": "班级一体机 / 交互白板软件合集：希沃白板工具、课堂管理、课表看板、随机点名…… 都是开源好物",
      "home.iwb-card-action": "打开 Awesome IWB",
      "home.iwb-card-url": "https://aiwb.smart-teach.cn/",
      "welcome.hello": "欢迎！(*￣3￣)╭",
      "welcome.intro": "欢迎使用ClassSoftwareHub下载站【v2.3.4 - Tangram】，收纳多款电教委员常用软件，感谢使用本网站！如果你觉得好的话可以考虑投喂作者哦！",
      "welcome.repository": "仓库地址",
      "welcome.explore": "开始探索下载~",
      "welcome.article": "相关文章",
      "welcome.article-url": "https://github.com/c1201y/ClassSoftwareHub/releases",
      "search.titlebar": "搜索软件、工具、AI 站点…",
      "search.placeholder": "搜索软件、内置工具、AI 站点，也可以只描述用途",
      "search.source-name": "应用名称",
      "search.source-intro": "相关简介",
      "search.clear": "清空关键词",
      "search.no-results": "没有找到与“{query}”相关的内容",
      "search.empty-hint": "换个关键词试试（比如「7-Zip」「计时」「二维码」「deepseek」）。想要的东西站里没有？到「提交软件」页说一声，或者进 QQ 群提。",
      "search.group-apps": "软件",
      "search.group-tools": "内置工具",
      "search.group-ai": "AI 导航",
      "search.group-pages": "页面",
      "search.page-home": "首页",
      "search.page-home-desc": "回到软件卡片列表",
      "search.page-tools": "内置工具",
      "search.page-tools-desc": "计时器、抽号、二维码、取色等在线小工具",
      "search.page-ai": "AI 导航",
      "search.page-ai-desc": "常用 AI 站点入口",
      "search.page-submit": "提交软件",
      "search.page-submit-desc": "推荐软件 / 反馈收录",
      "search.page-settings": "设置",
      "search.page-settings-desc": "主题、材质、节日皮肤、关于",
      "search.page-feedback": "反馈中心",
      "search.page-feedback-desc": "报告问题、提出建议",
      "search.keys-select": "选择",
      "search.keys-open": "打开",
      "search.keys-close": "关闭",
      "search.footer-note": "回车打开选中的结果；AI 导航的站点会在新标签页打开",
      "search.tools-hint": "要找工具？按 Ctrl + K 可以同时搜软件、内置工具和 AI 站点。",
      "search.tools-count": "共 {count} 个工具",
      "filter.all": "全部",
      // 分类筛选条右边的小字，{count} 会自动替换成已收录的软件数量
      "filter.collected": "本站目前已收录软件数量：{count}",
      "detail.intro": "应用介绍",
      "detail.info": "详细信息",
      "detail.version": "软件版本",
      "detail.size": "软件体积",
      "detail.system": "系统限制",
      "detail.website": "官方网站",
      "detail.download": "下载",
      "detail.not-found": "未找到该软件。",
      "detail.downloads": "下载",
      "detail.pending": "待补充",
      "detail.github": "GitHub",
      "detail.notice-title": "小提示",
      "detail.store-title": "使用 Microsoft Store 下载",
      "detail.store-desc": "由应用商店托管，安装后自动更新，不用手动跟版本。",
      "detail.store-button": "下载",
      "detail.store-only": "该软件通过 Microsoft Store 分发，点上方按钮打开商店页面即可获取",
      "detail.store-nostore": "本机没有「应用商店」（LTSC / 精简版 / 被卸载过）时，上面的商店按钮会打不开或反过来让你去商店里装商店。这时按 Win+R 输入 wsreset -i 回车，联网状态下 Windows 会自动把商店装回来（1–3 分钟，期间没有进度条）；若仍无效，用管理员身份打开 PowerShell 执行 winget install 9WZDNCRFJBMP。",
      "detail.mirror-button": "加速下载",
      "detail.mirror-hint": "不能下载？点我换个镜像",
      "detail.hash-copy": "复制",
      "detail.hash-copied": "已复制",
      "detail.hash-checksum": "校验值",
      "detail.mirror-desc": "这条路不一定每次都通（节点限速、被运营商拦、临时挂掉都有可能）。换下面任意一条再试，都是把同一个文件原样转发一份，国内下载通常快很多；也可以直接回上面点「下载」走 GitHub 官方。",
      "detail.mirror-note": "「本站加速节点」由本站自建维护，只做转发、不改动文件；其余为第三方公益镜像，随时可能失效或限速。装之前建议核对官方公布的哈希值。",
      // 下载项的落地方式：能直下的按钮写「下载」（点了本页直接开始下，不跳走）；
      // 只能跳转的按来源写「前往官网 / 前往网盘」，下面再补一句说明
      "detail.open-page": "前往官网",
      "detail.open-netdisk": "前往网盘",
      "detail.hint-page": "该软件只提供官方下载页，点按钮会跳转到官网获取安装包",
      "detail.hint-netdisk": "网盘分享，点按钮会跳转到网盘页面获取安装包",
      // 站内直链（OSS）下载：点按钮先换取一张 15 分钟的临时下载票据，再开始下载
      "detail.download-preparing": "正在准备下载…",
      "detail.download-quota": "本设备今天的下载次数已用完（每台设备每天 80 次），请明天再来。",
      "detail.download-failed": "下载链接获取失败，请稍后重试。",
      "detail.download-expired": "直连地址的有效期按文件大小分档（小文件只有几分钟）。若下载中断、或提示链接已过期，请回到本页重新点一次「下载」换取新链接。",
      "app.shortTitle": "电教委员常用软件下载站",
      "app.author": "Tiny-Nick",
      "app.version": "v2.3.4 - Tangram (20260927PR01)",
      "nav.submit": "提交软件",
      "submit.subtitle": "填写下面的信息，提交后进入审核队列，审核通过会自动上线。",
      "submit.import-title": "从 GitHub 一键读取",
      "submit.import-desc": "粘贴 GitHub 仓库地址后点「一键读取」，会自动读取软件名称、简介、版本号、支持系统，以及 Release 里各平台的安装包，填进下面的表单。国内访问 GitHub 偏慢，读取可能要等几秒。",
      "submit.import-placeholder": "https://github.com/所有者/仓库名（也可以直接填 所有者/仓库名）",
      "submit.import-button": "一键读取",
      "submit.import-reading": "读取中…",
      "submit.import-overwrite": "覆盖已填写的内容",
      "submit.import-overwrite-desc": "默认只填空白字段，不动你已经写好的内容；勾上后会用读取到的内容全部替换。",
      "submit.import-prerelease": "包含预发布版本（Beta / Alpha）",
      "submit.import-ok-title": "读取成功",
      "submit.import-summary": "已读取 {repo}：版本 {version}，找到 {count} 个安装包。（来源：{via}）",
      "submit.import-info-license": "许可证：{license}。",
      "submit.import-filled": "已填写",
      "submit.import-kept": "已保留原有内容",
      "submit.import-warnings": "需要注意",
      "submit.import-error-title": "读取失败",
      "submit.import-error-empty": "请先填 GitHub 仓库地址，例如 https://github.com/owner/repo",
      "submit.import-error-invalid": "这不像一个 GitHub 仓库地址，正确格式是 https://github.com/所有者/仓库名",
      "submit.import-error-notfound": "没找到这个仓库：请检查拼写，并确认它是公开仓库。",
      "submit.import-error-ratelimit": "GitHub 接口的访问次数用完了，请过一会儿再试，或手动填写。",
      "submit.import-error-network": "读取失败：{message}。可能是当前网络访问 GitHub 不通，可以稍后重试，或手动填写。",
      "submit.import-warn-release-failed": "只读取到仓库信息，未识别到 Release，下载项请手动补充。",
      "submit.import-warn-no-release": "该仓库还没有发布过 Release，下载项先填了 Release 页面链接。",
      "submit.import-warn-no-asset": "最新 Release 里没有可下载的文件，下载项先填了 Release 页面链接。",
      "submit.import-warn-skipped": "自动跳过了 {count} 个调试符号 / 校验文件之类的非安装包文件。",
      "submit.import-warn-truncated": "安装包比较多，只填了前 {count} 个，剩下的请手动补充。",
      "submit.import-warn-prerelease": "最新版 {tag} 是预发布版本（Beta / Alpha），上线前请确认是否合适。",
      "submit.import-warn-newer-prerelease": "更新的 {tag} 是预发布版本；需要收录的话，勾选「包含预发布版本」再读一次。",
      "submit.import-warn-archived": "该仓库已被作者归档，可能不再更新。",
      "submit.import-warn-icon": "图标先用了仓库所有者（{owner}）的头像，建议换成软件自己的图标。",
      "submit.import-warn-downloads-kept": "下载项里已经有内容，这次没有覆盖；想用读取到的安装包，请勾选「覆盖已填写的内容」再读一次。",
      "submit.import-id-taken": "软件 ID「{id}」本站已存在，已自动改成「{newId}」。",
      "submit.import-id-duplicate": "软件 ID「{id}」本站已经有了，记得换一个。",
      "submit.import-latest-platform": "GitHub 最新版",
      "submit.import-latest-note": "打开 Release 页面下载最新安装包",
      "submit.import-web": "网页",
      "submit.import-notice-prerelease": "当前收录的是官方预发布版本 {tag}（Beta / Alpha），可能不够稳定；建议到 GitHub Releases 下载最新正式版。",
      "submit.section-basic": "基本信息",
      "submit.section-extra": "补充信息",
      "submit.section-downloads": "下载项",
      "submit.required": "必填",
      "submit.id": "软件 ID",
      "submit.id-placeholder": "例如 notepad-plus-plus",
      "submit.id-desc": "唯一标识，全站不能重复，也是网址 #/download/<id> 的一部分；只用小写英文、数字和短横线",
      "submit.name": "软件名称",
      "submit.name-placeholder": "例如 Notepad++",
      "submit.icon": "图标链接",
      "submit.icon-placeholder": "https://... （可选，建议正方形）",
      "submit.category": "分类",
      "submit.category-placeholder": "请选择分类",
      "submit.tagline": "一句话简介",
      "submit.tagline-placeholder": "首页卡片上显示的那句",
      "submit.description": "详细介绍",
      "submit.description-placeholder": "软件是做什么的、有什么特点",
      "submit.contact": "联系方式",
      "submit.contact-placeholder": "QQ / 微信 / 邮箱都可以",
      "submit.contact-desc": "您的联系方式将在本地加密后提交，仅管理员可解密查看",
      "submit.version": "版本号",
      "submit.version-placeholder": "例如 8.6.9",
      "submit.size": "软件体积",
      "submit.size-placeholder": "例如 25 MB",
      "submit.system": "系统限制",
      "submit.system-placeholder": "例如 Windows 10/11 64位",
      "submit.website": "官方网站",
      "submit.website-placeholder": "https://...",
      "submit.github": "GitHub 仓库",
      "submit.github-placeholder": "https://github.com/...",
      "submit.notice": "更新提示 notice",
      "submit.notice-placeholder": "可选，更新频繁的软件建议填写",
      "submit.store": "Microsoft Store 链接",
      "submit.store-placeholder": "https://apps.microsoft.com/... （可选）",
      "submit.sort": "排序 sort",
      "submit.sort-placeholder": "默认 99，数字越小越靠前",
      "submit.download-index": "下载项 {index}",
      "submit.download-platform": "平台 / 架构",
      "submit.download-platform-placeholder": "例如 Windows x64 安装版",
      "submit.download-size": "体积",
      "submit.download-note": "备注",
      "submit.download-note-placeholder": "可选",
      "submit.download-url-locked": "这条直链由本站在上传后自动生成，已锁定不可修改；要换文件请重新上传。",
      "submit.download-url": "文件直链",
      "submit.download-url-placeholder": "https://... .exe / .zip / .msi",
      "submit.download-hash": "校验值",
      "submit.download-hash-placeholder": "选填，例如 32E196DA…（十六进制）",
      "submit.download-hash-desc": "只填十六进制值，不用写算法名，网页按位数自动识别",
      "submit.download-kind": "下载方式",
      "submit.download-kind-auto": "自动识别（按链接判断）",
      "submit.download-kind-file": "官网直链 / 直接下载",
      "submit.download-kind-netdisk": "网页跳转",
      "submit.download-kind-store": "应用商店",
      "submit.download-upload": "上传文件",
      "submit.icon-upload": "选择图标文件",
      "submit.icon-upload-note": "可选：选一张本地图片，上传后自动填入图标链接， 体积＜1MB",
      "submit.icon-too-large": "图标文件太大（{size}），请换一张 {limit} 以内的图片。",
      "submit.uploading": "上传中…",
      "submit.uploading-percent": "上传中 {percent}%",
      "submit.upload-limit-note": "单个文件上限 {limit}",
      "submit.upload-large-warn": "文件较大（{size}），上传会比较慢，完成后请勿关闭页面。",
      "submit.upload-too-large": "文件太大：{size}，超过本站 {limit} 的上传上限。请改用官网 / GitHub Releases 的下载直链或外部网盘链接提交。",
      "submit.upload-server-limit": "文件太大：超过本站 {limit} 的上传上限。请改用官网 / GitHub Releases 直链或外部网盘链接提交。",
      "submit.upload-network-error": "网络中断，上传失败。请检查网络后重试。",
      "submit.upload-failed": "上传失败：{message}",
      "submit.upload-sign-failed": "上传服务暂时不可用，请稍后重试。",
      "submit.upload-rejected": "上传被对象存储拒绝（{detail}）。请稍后重试，或改用外部网盘链接。",
      "submit.upload-notconfigured": "上传服务未配置，请联系维护者",
      "submit.upload-ttl-warn": "请在 {minutes} 分钟内完成提交：超时未提交的附件会被自动清理，需要重新上传。要换文件同样请重新上传一份 —— 已经传上来的那份不会跟着你本地改的文件变。",
      "submit.download-add": "添加下载项",
      "submit.download-limit": "一个软件最多 5 个下载项，已经到上限了。更多版本请在详情里给官网或 GitHub Releases 链接。",
      "submit.download-remove": "删除",
      "submit.submit": "提交",
      "submit.submitting": "提交中…",
      "submit.error-required": "请填写带 * 的必填项",
      "submit.error-encrypt": "联系方式加密失败，内容没有提交。请检查网络后重试；仍失败请直接到 GitHub 仓库提 Issue 联系管理员。",
      "submit.error-id": "软件 ID 只能用小写英文、数字和短横线，且不能以短横线开头（例：notepad-plus-plus、7-zip）。它会成为网址的一部分，也会被用来命名数据文件，所以不能有别的字符。",
      "submit.error-sort": "排序只能是数字（越小越靠前）。留空表示排在最后，不要填文字。",
      "submit.error-hash": "下载项 {index} 的校验值格式不对：只填十六进制字符，位数应为 32 / 40 / 56 / 64 / 96 / 128（对应 MD5 / SHA-1 / SHA-224 / SHA-256 / SHA-384 / SHA-512）",
      "submit.error-network": "网络错误：{message}",
      "submit.error-timeout": "请求超时（{seconds} 秒无响应）",
      "submit.error-unexpected": "提交服务返回了无法识别的内容",
      "submit.result-success-title": "提交成功",
      "submit.result-success": "已进入审核队列，管理员审核通过后会自动上线。",
      "submit.result-error-title": "提交失败",
      "submit.result-error": "请稍后重试，或到仓库提 Issue 反馈。",
      "submit.fallback-title": "提交服务连不上",
      "submit.fallback-desc": "提交服务没连上（部分地区对境外流量的限制，或浏览器、网络环境异常，都会这样）。你填的内容没有丢，可以过一段时间再试，也可以直接交到 GitHub。",
      "submit.fallback-retry": "重试提交",
      "submit.fallback-download": "下载提交文件",
      "submit.fallback-copy": "复制内容",
      "submit.fallback-copied": "已复制",
      "submit.fallback-github": "去 GitHub 提交",
      "submit.fallback-github-hint": "点开链接后把刚下载的 JSON 内容贴进去（放在 submissions/ 目录下，文件名用 .json 结尾）再提交。这一步需要登录 GitHub 账号；没有写入权限时 GitHub 会引导你先 fork 并创建 PR，合并后同样进入审核队列。",
      "submit.fallback-restore": "恢复上次填写",
      "submit.fallback-restore-title": "已恢复填写",
      "submit.fallback-restored": "已把上次没提交成功的内容填回表单，可以直接点「提交」重试。",
      // ── 反馈中心（#/feedback）────────────────────────────────────────────
      // 用户在这里报告问题 / 提建议，提交时生成 GitHub Issue 预填链接（本站无后端）。
      // 分类是两层的：kind 两级（报告 / 建议），只有「报告问题」才有子类型 sub-*。
      // 改文案只动引号里的字；分几张卡片、几个子类型由 src/gallery/feedback.ts 决定。
      "feedback.title": "帮助改进 ClassSoftwareHub",
      "feedback.subtitle": "报告软件信息错误、下载链接失效或其他使用问题；也可以提出功能建议。每条反馈都会进入公开的议题列表，由维护者跟进。",
      // 选择态「接下来会怎样」三步说明
      "feedback.flow-title": "提交后的处理流程",
      "feedback.flow-step-1-title": "填写反馈信息",
      "feedback.flow-step-1-desc": "选择反馈类型，说明问题或建议。填写内容将在本地自动保存为草稿，中途离开亦不会丢失。",
      "feedback.flow-step-2-title": "提交反馈",
      "feedback.flow-step-2-desc": "点击「提交反馈」，内容直接进入公开议题列表 —— 不用登录 GitHub，也不用跳出本站。",
      "feedback.flow-step-3-title": "维护者跟进处理",
      "feedback.flow-step-3-desc": "反馈将进入公开议题列表，处理进度可在议题下方查看，亦可继续补充说明。",
      // 已有反馈入口
      "feedback.existing-title": "请先查阅已有反馈",
      "feedback.existing-desc": "已有反馈均记录于公开议题列表中，建议先行搜索关键词，以避免重复提交。",
      "feedback.existing-open": "查看议题列表",
      "feedback.kind-report": "报告问题",
      "feedback.kind-report-desc": "软件信息有误、下载链接失效，或页面无法正常使用",
      "feedback.kind-suggestion": "提出建议",
      "feedback.kind-suggestion-desc": "希望新增的功能，或对现有功能的改进建议",
      "feedback.back": "返回",
      "feedback.back-to-kinds": "重新选择反馈类型",
      "feedback.section-basic": "基本信息",
      "feedback.section-contact": "联系方式",
      "feedback.sub-kind": "问题类型",      "feedback.sub-kind-placeholder": "请选择",
      "feedback.sub-interaction": "逻辑交互问题",
      "feedback.sub-link": "链接失效问题",
      "feedback.sub-other": "其他分类问题",
      "feedback.app": "涉及的软件",
      "feedback.app-placeholder": "选择软件（选填）",
      "feedback.subject": "标题",
      "feedback.subject-placeholder": "请用一句话概括问题或建议",
      "feedback.detail": "详细描述",
      "feedback.detail-placeholder": "请说明问题出现的页面、操作步骤、预期结果与实际结果",
      "feedback.contact": "联系方式",
      "feedback.contact-placeholder": "QQ / 微信 / 邮箱",
      "feedback.contact-desc": "选填。您的联系方式将在本地加密后提交，仅维护者可解密查看。",
      "feedback.submit": "提交反馈",
      "feedback.submitting": "正在提交…",
      "feedback.fallback-github": "改用 GitHub 提交",
      "feedback.success-title": "反馈已提交",
      "feedback.success-desc": "感谢反馈！内容已进入公开议题列表，维护者会尽快跟进。",
      "feedback.copy": "复制反馈内容",
      "feedback.copied": "已复制",
      "feedback.restore": "恢复上次填写",
      "feedback.privacy-title": "内容将公开可见",
      "feedback.privacy-desc": "提交后，您填写的内容将公开显示于本站仓库的议题列表中，任何人均可查看。请勿填写密码、手机号等敏感信息。",
      "feedback.github-hint": "点击「提交反馈」即可，无需 GitHub 账号。标题与正文会提交到本站的提交服务，随后出现在公开议题列表里；选填的联系方式已在本地加密，仅维护者可解密查看。",
      "feedback.error-title": "无法提交",
      "feedback.error-required": "请填写所有标有 * 的必填项",
      "feedback.error-kind": "请选择反馈类型",
      "feedback.error-sub-kind": "请选择问题类型",
      "feedback.error-title-too-long": "标题超出 {max} 字上限，请精简后重试",
      "feedback.error-encrypt": "联系方式加密失败，请稍后重试。若反复失败，可改用「复制反馈内容」通过 QQ 群联系维护者",
      "feedback.error-network": "没能连上提交服务，请检查网络后重试，或改用「复制反馈内容」把内容发给维护者。",
      "feedback.error-timeout": "提交超时（{seconds} 秒），请稍后重试。",
      "feedback.truncated-title": "内容已自动截断",
      "feedback.truncated-desc": "描述长度超出链接可承载的上限，已自动截断。请点击「复制反馈内容」，将完整内容粘贴到议题正文中。",
      "feedback.popup-blocked-title": "新窗口被浏览器拦截",
      "feedback.popup-blocked-desc": "反馈内容已复制到剪贴板。请在浏览器中允许本站弹出窗口后重试，或直接粘贴已复制的内容。"
    };
