// ════════════════════════════════════════════════════════════════════
// ★★★★★ 全站文字设置区（中文）★★★★★
// 原版 HTML 里这块叫 window.DOWNLOAD_STATION_TEXT —— 全站文字就集中在
// 这一个地方。本文件放在项目根目录，打开就能改。
//
// 【日常改文字 = 只改这个文件】建议只改引号里的文字，不要动左边的 key
// （key 是页面找文字的“编号”，例如 home.title，改错就找不到文字了）。
// 改完保存：npm run dev 下浏览器自动刷新；发布前跑 npm run build
// 或 npm run build:single。
//
// 英文站文字在 src/gallery/Strings/en-US/Resources.ts（和这里一一对应，
// 中文站改了顺手同步英文站；只维护中文站可不管它）。
// 软件数据（软件名/简介/下载链接不在这里）→ 根目录「软件数据」文件夹。
//
// key 速查：app.*=站名/版权/版本号；home.*=首页标题区+下载HTML按钮+
//             「教学辅助」分类顶部的外链推荐卡（home.iwb-card-*）；
// filter.*=筛选条；detail.*=详情页；text.*=通用按钮/设置页；
// about.*=设置页“关于”区（*-url 是链接地址；QQ 群入口=about.qq-group(+url)）。
// welcome.*=欢迎弹窗（进入网站时弹出；仓库/作者/QQ 群链接复用 about.*-url 键；
//           相关文章=welcome.article(+url)，投喂作者=about.reward(+url)）。
// search.*=标题栏搜索框（placeholder、选项里“来源”的称呼、无结果提示）。
// ════════════════════════════════════════════════════════════════════
export default {
      "app.title": "电教委员常用软件下载站",
      "text.back": "返回",
      "text.copy": "复制",
      "text.more": "更多",
      "text.navigation-menu": "导航菜单",
      "text.search": "搜索",
      "text.select": "选择",
      "text.select-all": "全选",
      "text.default-navigation-transition-info": "默认 (DefaultNavigationTransitionInfo)",
      "text.entrance-navigation-transition-info": "进入 (EntranceNavigationTransitionInfo)",
      "text.drill-in-navigation-transition-info": "钻取 (DrillInNavigationTransitionInfo)",
      "text.suppress-navigation-transition-info": "无动画 (SuppressNavigationTransitionInfo)",
      "text.slide-navigation-transition-info-from-right": "滑动 (SlideNavigationTransitionInfo, Effect = FromRight)",
      "text.slide-navigation-transition-info-from-left": "滑动 (SlideNavigationTransitionInfo, Effect = FromLeft)",
      "text.common-navigation-transition-info": "通用 (CommonNavigationTransitionInfo)",
      "text.continuum-navigation-transition-info": "连续 (ContinuumNavigationTransitionInfo)",
      "text.about-copyright": "© {year} {author}。{rights}",
      "theme-toggle": "切换主题",
      "favorite-toggle": "收藏",
      "text.about": "关于",
      "text.acrylic": "Acrylic",
      "text.all-rights-reserved": "",
      "text.animation-style-when-switching-pages": "切换页面时的动画样式",
      "text.appearance": "外观",
      "text.choose-the-app-background-material": "选择应用背景材质",
      "text.choose-your-app-color-mode": "选择应用颜色模式",
      "text.holiday-skin": "节日皮肤",
      "text.holiday-skin-desc": "节日档期内自动换上应景横幅与主题色（中秋 / 国庆）；档期外也可以手动打开。",
      "text.on": "开启",
      "text.off": "关闭",
      "text.dark": "深色",
      "text.discord-group": "Discord 群组",
      "text.left": "左侧",
      "text.light": "浅色",
      "text.material": "材质",
      "text.mica": "Mica",
      "text.navigation-pane-position": "导航窗格位置",
      "text.open-code-repository": "打开代码仓库",
      "about.author-home": "作者首页",
      "about.author-home-url": "https://space.bilibili.com/1274920807",
      "about.echo-cave": "回声洞",
      "about.echo-cave-url": "https://www.bilibili.com/video/BV1GJ411x7h7/",
      // QQ 群入口（「关于」区 + 首页欢迎弹窗都用这两条）
      "about.qq-group": "加入 QQ 群",
      "about.qq-group-url": "https://qm.qq.com/q/wByO7XG8Wk",
      "about.reward": "投喂作者",
      "about.reward-url": "https://ifdian.net/a/TinyNickCSHub",
      "about.repository-url": "https://github.com/c1201y/ClassSoftwareHub",
      // 「关于」里的 UI 内核链接：本站界面用的上游组件库 WinUIonWeb（致敬原作者）
      "about.ui-kernel": "UI 内核（WinUIonWeb）",
      "about.ui-kernel-url": "https://github.com/Furry-Xiyi/WinUIonWeb",
      "text.page-transition": "页面过渡",
      "text.qq-group": "QQ 群组",
      "text.select-the-navigation-bar-position": "选择导航栏位置",
      "text.settings": "设置",
      "text.theme": "主题",
      "text.top": "顶部",
      "text.use-system-setting": "使用系统设置",
      "nav.home": "首页",
      "home.title": "ClassSoftwareHub",
      "home.subtitle": "欢迎使用下载站【v2.3.0 - September 18 Incident】，欢迎各位添砖加瓦，感谢 @Bilibili 椰汁cyan 提供网站的搭建！",
      "home.download-html": "使用 HTML【开发者】",
      "home.download-html-tip": "可以在网络通畅时下载本站，后离线也可访问！",
      "home.download-html-filename": "电教委员常用软件下载站.html",
      "home.download-template": "下载软件添加模板【开发者】",
      "home.download-template-tip": "共创！添加软件使用的模板",
      "home.download-template-filename": "模板.json",
      "home.download-html-only-single": "当前打开的页面不是离线单文件版（开发/预览模式下导出的文件会缺少脚本和样式，无法离线使用）。\n请先运行 npm run build:single 打包，再打开 dist 文件夹里生成的 HTML，使用此功能下载。",
      // ★首页「教学辅助」分类顶部的外链推荐卡（Awesome IWB）
      //   想换推荐的网站/改文案：只动下面这 4 个 key。
      //   url 填完整网址（https:// 开头）；把 title 和 desc 都留空("")这张卡就不显示。
      "home.iwb-card-title": "想找更多教学软件？去 Awesome IWB 逛逛",
      "home.iwb-card-desc": "班级一体机 / 交互白板软件合集：希沃白板工具、课堂管理、课表看板、随机点名…… 都是开源好物",
      "home.iwb-card-action": "打开 Awesome IWB",
      "home.iwb-card-url": "https://aiwb.smart-teach.cn/",
      "welcome.hello": "欢迎！(*￣3￣)╭",
      "welcome.intro": "欢迎使用ClassSoftwareHub下载站【v2.3.0 - September 18 Incident】，收纳多款电教委员常用软件，感谢使用本网站！如果你觉得好的话可以考虑投喂作者哦！",
      "welcome.repository": "仓库地址",
      "welcome.explore": "开始探索下载~",
      "welcome.article": "相关文章",
      "welcome.article-url": "https://github.com/c1201y/ClassSoftwareHub/releases",
      "search.placeholder": "搜索软件，不需要知道软件名！",
      "search.source-name": "应用名称",
      "search.source-intro": "相关简介",
      "search.no-results": "没有找到与“{query}”相关的软件",
      "filter.all": "全部",
      // 分类筛选条右边的小字，{count} 会自动替换成已收录的软件数量
      "filter.collected": "本站目前已收录软件数量：{count}",
      "detail.intro": "应用介绍",
      "detail.info": "详细信息",
      "detail.version": "软件版本",
      "detail.size": "软件体积",
      "detail.system": "系统限制",
      "detail.website": "官方网站",
      "detail.download": "下载",
      "detail.not-found": "未找到该软件。",
      "detail.downloads": "下载",
      "detail.pending": "待补充",
      "detail.github": "GitHub",
      "detail.notice-title": "小提示",
      "detail.store-title": "使用 Microsoft Store 下载",
      "detail.store-desc": "由应用商店托管，安装后自动更新，不用手动跟版本。",
      "detail.store-button": "下载",
      "detail.store-only": "该软件通过 Microsoft Store 分发，点上方按钮打开商店页面即可获取",
      "app.shortTitle": "电教委员常用软件下载站",
      "app.author": "Tiny-Nick",
      "app.version": "v2.3.0 - September 18 Incident (20260916PR03)",
      "nav.submit": "提交软件",
      "submit.subtitle": "填写下面的信息，提交后进入审核队列，审核通过会自动上线。",
      "submit.import-title": "从 GitHub 一键读取",
      "submit.import-desc": "粘贴 GitHub 仓库地址后点「一键读取」，会自动读取软件名称、简介、版本号、支持系统，以及 Release 里各平台的安装包，填进下面的表单。国内访问 GitHub 偏慢，读取可能要等几秒。",
      "submit.import-placeholder": "https://github.com/所有者/仓库名（也可以直接填 所有者/仓库名）",
      "submit.import-button": "一键读取",
      "submit.import-reading": "读取中…",
      "submit.import-overwrite": "覆盖已填写的内容",
      "submit.import-overwrite-desc": "默认只填空白字段，不动你已经写好的内容；勾上后会用读取到的内容全部替换。",
      "submit.import-prerelease": "包含预发布版本（Beta / Alpha）",
      "submit.import-ok-title": "读取成功",
      "submit.import-summary": "已读取 {repo}：版本 {version}，找到 {count} 个安装包。（来源：{via}）",
      "submit.import-info-license": "许可证：{license}。",
      "submit.import-filled": "已填写",
      "submit.import-kept": "已保留原有内容",
      "submit.import-warnings": "需要注意",
      "submit.import-error-title": "读取失败",
      "submit.import-error-empty": "请先填 GitHub 仓库地址，例如 https://github.com/owner/repo",
      "submit.import-error-invalid": "这不像一个 GitHub 仓库地址，正确格式是 https://github.com/所有者/仓库名",
      "submit.import-error-notfound": "没找到这个仓库：请检查拼写，并确认它是公开仓库。",
      "submit.import-error-ratelimit": "GitHub 接口的访问次数用完了（未登录每小时 60 次），请过一会儿再试，或手动填写。",
      "submit.import-error-network": "读取失败：{message}。可能是当前网络访问 GitHub 不通，可以稍后重试，或手动填写。",
      "submit.import-warn-release-failed": "只读到了仓库信息，没读到 Release（接口被限流或网络中断），下载项请手动补充。",
      "submit.import-warn-no-release": "该仓库还没有发布过 Release，下载项先填了 Release 页面链接。",
      "submit.import-warn-no-asset": "最新 Release 里没有可下载的文件，下载项先填了 Release 页面链接。",
      "submit.import-warn-skipped": "自动跳过了 {count} 个调试符号 / 校验文件之类的非安装包文件。",
      "submit.import-warn-truncated": "安装包比较多，只填了前 {count} 个，剩下的请手动补。",
      "submit.import-warn-prerelease": "最新版 {tag} 是预发布版本（Beta / Alpha），上线前请确认是否合适。",
      "submit.import-warn-newer-prerelease": "更新的 {tag} 是预发布版本；需要收录的话，勾选「包含预发布版本」再读一次。",
      "submit.import-warn-archived": "该仓库已被作者归档，可能不再更新。",
      "submit.import-warn-icon": "图标先用了仓库所有者（{owner}）的头像，建议换成软件自己的图标。",
      "submit.import-warn-downloads-kept": "下载项里已经有内容，这次没有覆盖；想用读取到的安装包，请勾选「覆盖已填写的内容」再读一次。",
      "submit.import-id-taken": "软件 ID「{id}」本站已存在，已自动改成「{newId}」。",
      "submit.import-id-duplicate": "软件 ID「{id}」本站已经有了，记得换一个。",
      "submit.import-latest-platform": "GitHub 最新版",
      "submit.import-latest-note": "打开 Release 页面下载最新安装包",
      "submit.import-web": "网页",
      "submit.import-notice-prerelease": "当前收录的是官方预发布版本 {tag}（Beta / Alpha），可能不够稳定；建议到 GitHub Releases 下载最新正式版。",
      "submit.section-basic": "基本信息",
      "submit.section-extra": "补充信息",
      "submit.section-downloads": "下载项",
      "submit.required": "必填",
      "submit.id": "软件 ID",
      "submit.id-placeholder": "例如 notepad-plus-plus",
      "submit.id-desc": "唯一标识，全站不能重复，也是网址 #/download/<id> 的一部分；只用小写英文、数字和短横线",
      "submit.name": "软件名称",
      "submit.name-placeholder": "例如 Notepad++",
      "submit.icon": "图标链接",
      "submit.icon-placeholder": "https://... （可选，建议正方形）",
      "submit.category": "分类",
      "submit.category-placeholder": "请选择分类",
      "submit.tagline": "一句话简介",
      "submit.tagline-placeholder": "首页卡片上显示的那句",
      "submit.description": "详细介绍",
      "submit.description-placeholder": "软件是做什么的、有什么特点",
      "submit.version": "版本号",
      "submit.version-placeholder": "例如 8.6.9",
      "submit.size": "软件体积",
      "submit.size-placeholder": "例如 25 MB",
      "submit.system": "系统限制",
      "submit.system-placeholder": "例如 Windows 10/11 64位",
      "submit.website": "官方网站",
      "submit.website-placeholder": "https://...",
      "submit.github": "GitHub 仓库",
      "submit.github-placeholder": "https://github.com/...",
      "submit.notice": "更新提示 notice",
      "submit.notice-placeholder": "可选，更新频繁的软件建议填写",
      "submit.store": "Microsoft Store 链接",
      "submit.store-placeholder": "https://apps.microsoft.com/... （可选）",
      "submit.sort": "排序 sort",
      "submit.sort-placeholder": "默认 99，数字越小越靠前",
      "submit.download-index": "下载项 {index}",
      "submit.download-platform": "平台 / 架构",
      "submit.download-platform-placeholder": "例如 Windows x64 安装版",
      "submit.download-size": "体积",
      "submit.download-note": "备注",
      "submit.download-note-placeholder": "可选",
      "submit.download-url": "文件直链",
      "submit.download-url-placeholder": "https://... .exe / .zip / .msi",
      "submit.download-add": "添加下载项",
      "submit.download-remove": "删除",
      "submit.submit": "提交",
      "submit.submitting": "提交中…",
      "submit.error-required": "请填写带 * 的必填项",
      "submit.error-network": "网络错误：{message}",
      "submit.error-timeout": "请求超时（{seconds} 秒无响应）",
      "submit.error-unexpected": "提交服务返回了无法识别的内容",
      "submit.result-success-title": "提交成功",
      "submit.result-success": "已进入审核队列，管理员审核通过后会自动上线。",
      "submit.result-error-title": "提交失败",
      "submit.result-error": "请稍后重试，或到仓库提 Issue 反馈。",
      "submit.fallback-title": "提交服务连不上",
      "submit.fallback-desc": "提交服务没连上（部分地区对境外流量的限制，或浏览器、网络环境异常，都会这样）。你填的内容没有丢，可以过一段时间再试，也可以直接交到 GitHub。",
      "submit.fallback-retry": "重试提交",
      "submit.fallback-download": "下载提交文件",
      "submit.fallback-copy": "复制内容",
      "submit.fallback-copied": "已复制",
      "submit.fallback-github": "去 GitHub 提交",
      "submit.fallback-github-hint": "点开链接后把刚下载的 JSON 内容贴进去（放在 submissions/ 目录下，文件名用 .json 结尾）再提交。这一步需要登录 GitHub 账号；没有写入权限时 GitHub 会引导你先 fork 并创建 PR，合并后同样进入审核队列。",
      "submit.fallback-restore": "恢复上次填写",
      "submit.fallback-restore-title": "已恢复填写",
      "submit.fallback-restored": "已把上次没提交成功的内容填回表单，可以直接点「提交」重试。"
    };
