// English (en-US) resources of the download station.
export default {
    "app.title": "Software Download Station",
    "text.back": "Back",
    "text.copy": "Copy",
    "text.more": "More",
    "text.navigation-menu": "Navigation menu",
    "text.search": "Search",
    "text.select": "Select",
    "text.select-all": "Select all",
    "text.default-navigation-transition-info": "DefaultNavigationTransitionInfo",
    "text.entrance-navigation-transition-info": "EntranceNavigationTransitionInfo",
    "text.drill-in-navigation-transition-info": "DrillInNavigationTransitionInfo",
    "text.suppress-navigation-transition-info": "SuppressNavigationTransitionInfo",
    "text.slide-navigation-transition-info-from-right": "SlideNavigationTransitionInfo (Effect = FromRight)",
    "text.slide-navigation-transition-info-from-left": "SlideNavigationTransitionInfo (Effect = FromLeft)",
    "text.common-navigation-transition-info": "CommonNavigationTransitionInfo",
    "text.continuum-navigation-transition-info": "ContinuumNavigationTransitionInfo",
    "text.about-copyright": "© {year} {author}. {rights}",
    "theme-toggle": "Toggle theme",
    "favorite-toggle": "Favorite",
    "text.about": "About",
    "text.acrylic": "Acrylic",
    "text.all-rights-reserved": "All rights reserved.",
    "text.animation-style-when-switching-pages": "Animation style when switching pages",
    "text.appearance": "Appearance",
    "text.choose-the-app-background-material": "Choose the app background material",
    "text.choose-your-app-color-mode": "Choose your app color mode",
    "text.holiday-skin": "Holiday skin",
    "text.holiday-skin-desc": "Turns on automatically during the holiday window (Mid-Autumn / National Day); you can also switch it on manually at any time.",
    "text.on": "On",
    "text.off": "Off",
    "text.dark": "Dark",
    "text.left": "Left",
    "text.light": "Light",
    "text.material": "Material",
    "text.mica": "Mica",
    "text.navigation-pane-position": "Navigation pane position",
    "text.open-code-repository": "Open code repository",
    "about.author-home": "Author Home",
    "about.author-home-url": "https://space.bilibili.com/1274920807",
    "about.echo-cave": "Echo Cave",
    "about.echo-cave-url": "https://www.bilibili.com/video/BV1GJ411x7h7/",
    "about.repository-url": "https://github.com/Furry-Xiyi/WinUIonWeb/",
    "text.page-transition": "Page Transition",
    "text.select-the-navigation-bar-position": "Select the navigation bar position",
    "text.settings": "Settings",
    "text.theme": "Theme",
    "text.top": "Top",
    "text.use-system-setting": "Use system setting",
    "nav.home": "Software Download Station",
    "home.title": "Software Download Station",
    "home.subtitle": "For classroom teaching and office use · Click a card for details",
    "home.download-html": "⬇ Download HTML",
    "home.download-html-tip": "Download this site while online so you can use it offline later!",
    "home.download-html-filename": "Software-Download-Station.html",
    "home.download-template": "⬇ Download software-list template",
    "home.download-template-tip": "Use this when adding a new software entry (the file explains the format)",
    "home.download-template-filename": "software-list-template.json",
    "home.download-html-only-single": "This page is not the single-file offline build. Exporting from a dev/preview build would produce an incomplete file (missing scripts & styles).\nPlease run npm run build:single first, then open the generated HTML in the dist folder and use this button there.",
    "welcome.hello": "Welcome! (*￣3￣)╭",
    "welcome.intro": "Welcome to the ClassSoftwareHub download station, packed with handy apps for class IT commissioners. Thanks for visiting!",
    "welcome.repository": "Repository",
    "welcome.explore": "Start Exploring ~",
    "welcome.article": "Related Articles",
    "welcome.article-url": "https://www.bilibili.com/opus/1245751454573002769",
    "search.placeholder": "Search apps (name / intro / description)",
    "search.source-name": "App name",
    "search.source-intro": "Description",
    "search.no-results": "No apps match “{query}”",
    "filter.all": "All",
    "detail.intro": "About",
    "detail.info": "Details",
    "detail.version": "Version",
    "detail.size": "Size",
    "detail.website": "Website",
    "detail.download": "Download",
    "detail.not-found": "Software not found.",
    "app.shortTitle": "Software Download Station",
    "app.author": "惜忆想睡觉",
    "app.version": "1.0.0-Insider",
    "detail.downloads": "Downloads",
    "detail.pending": "TBD",
    "detail.github": "GitHub",
    "detail.notice-title": "Heads-up",
    "detail.store-title": "Get it from Microsoft Store",
    "detail.store-desc": "Hosted by Microsoft Store and keeps itself up to date automatically.",
    "detail.store-button": "Open Microsoft Store",
    "detail.store-only": "This app is distributed through Microsoft Store. Use the button above to open its Store page — the Store version updates itself automatically.",
  "detail.system": "System requirements",
  "about.reward": "Reward the author",
  "about.reward-url": "https://ifdian.net/a/TinyNickCSHub",
  };
