// English (en-US) resources of the download station.
export default {
    "app.title": "Software Download Station",
    "text.back": "Back",
    "text.copy": "Copy",
    "text.more": "More",
    "text.navigation-menu": "Navigation menu",
    "text.search": "Search",
    "text.select": "Select",
    "text.select-all": "Select all",
    "text.default-navigation-transition-info": "DefaultNavigationTransitionInfo",
    "text.entrance-navigation-transition-info": "EntranceNavigationTransitionInfo",
    "text.drill-in-navigation-transition-info": "DrillInNavigationTransitionInfo",
    "text.suppress-navigation-transition-info": "SuppressNavigationTransitionInfo",
    "text.slide-navigation-transition-info-from-right": "SlideNavigationTransitionInfo (Effect = FromRight)",
    "text.slide-navigation-transition-info-from-left": "SlideNavigationTransitionInfo (Effect = FromLeft)",
    "text.common-navigation-transition-info": "CommonNavigationTransitionInfo",
    "text.continuum-navigation-transition-info": "ContinuumNavigationTransitionInfo",
    "text.about-copyright": "© {year} {author}. {rights}",
    "theme-toggle": "Toggle theme",
    "favorite-toggle": "Favorite",
    "text.about": "About",
    "text.acrylic": "Acrylic",
    "text.all-rights-reserved": "All rights reserved.",
    "text.animation-style-when-switching-pages": "Animation style when switching pages",
    "text.appearance": "Appearance",
    "text.choose-the-app-background-material": "Choose the app background material",
    "text.choose-your-app-color-mode": "Choose your app color mode",
    "text.holiday-skin": "Holiday skin",
    "text.holiday-skin-desc": "Turns on automatically during the holiday window (Mid-Autumn / National Day); you can also switch it on manually at any time.",
    "text.on": "On",
    "text.off": "Off",
    "text.dark": "Dark",
    "text.left": "Left",
    "text.light": "Light",
    "text.material": "Material",
    "text.mica": "Mica",
    "text.navigation-pane-position": "Navigation pane position",
    "text.open-code-repository": "Open code repository",
    "about.author-home": "Author Home",
    "about.author-home-url": "https://space.bilibili.com/1274920807",
    "about.echo-cave": "Echo Cave",
    "about.echo-cave-url": "https://www.bilibili.com/video/BV1GJ411x7h7/",
    "about.repository-url": "https://github.com/Furry-Xiyi/WinUIonWeb/",
    "text.page-transition": "Page Transition",
    "text.select-the-navigation-bar-position": "Select the navigation bar position",
    "text.settings": "Settings",
    "text.theme": "Theme",
    "text.top": "Top",
    "text.use-system-setting": "Use system setting",
    "nav.home": "Software Download Station",
    "home.title": "Software Download Station",
    "home.subtitle": "For classroom teaching and office use · Click a card for details",
    "home.download-html": "⬇ Download HTML",
    "home.download-html-tip": "Download this site while online so you can use it offline later!",
    "home.download-html-filename": "Software-Download-Station.html",
    "home.download-template": "⬇ Download software-list template",
    "home.download-template-tip": "Use this when adding a new software entry (the file explains the format)",
    "home.download-template-filename": "software-list-template.json",
    "home.download-html-only-single": "This page is not the single-file offline build. Exporting from a dev/preview build would produce an incomplete file (missing scripts & styles).\nPlease run npm run build:single first, then open the generated HTML in the dist folder and use this button there.",
    "welcome.hello": "Welcome! (*￣3￣)╭",
    "welcome.intro": "Welcome to the ClassSoftwareHub download station, packed with handy apps for class IT commissioners. Thanks for visiting!",
    "welcome.repository": "Repository",
    "welcome.explore": "Start Exploring ~",
    "welcome.article": "Related Articles",
    "welcome.article-url": "https://www.bilibili.com/opus/1245751454573002769",
    "search.placeholder": "Search apps (name / intro / description)",
    "search.source-name": "App name",
    "search.source-intro": "Description",
    "search.no-results": "No apps match “{query}”",
    "filter.all": "All",
    "detail.intro": "About",
    "detail.info": "Details",
    "detail.version": "Version",
    "detail.size": "Size",
    "detail.website": "Website",
    "detail.download": "Download",
    "detail.not-found": "Software not found.",
    "app.shortTitle": "Software Download Station",
    "app.author": "惜忆想睡觉",
    "app.version": "1.0.0-Insider",
    "detail.downloads": "Downloads",
    "detail.pending": "TBD",
    "detail.github": "GitHub",
    "detail.notice-title": "Heads-up",
    "detail.store-title": "Get it from Microsoft Store",
    "detail.store-desc": "Hosted by Microsoft Store and keeps itself up to date automatically.",
    "detail.store-button": "Open Microsoft Store",
    "detail.store-only": "This app is distributed through Microsoft Store. Use the button above to open its Store page — the Store version updates itself automatically.",
    "nav.submit": "Submit an app",
    "submit.subtitle": "Fill in the details below. Submissions enter a review queue and go live once approved.",
    "submit.import-title": "Read from GitHub",
    "submit.import-desc": "Paste a GitHub repository URL and click the button: the name, description, version, supported systems and every release asset get filled into the form below. GitHub can be slow to reach, so this may take a few seconds.",
    "submit.import-placeholder": "https://github.com/owner/repo (owner/repo also works)",
    "submit.import-button": "Read now",
    "submit.import-reading": "Reading…",
    "submit.import-overwrite": "Overwrite what I already typed",
    "submit.import-overwrite-desc": "By default only empty fields are filled. Tick this to replace everything with what was read.",
    "submit.import-prerelease": "Include pre-releases (Beta / Alpha)",
    "submit.import-ok-title": "Loaded",
    "submit.import-summary": "Read {repo}: version {version}, {count} download(s) found. (via {via})",
    "submit.import-info-license": "License: {license}.",
    "submit.import-filled": "Filled in",
    "submit.import-kept": "Kept as-is",
    "submit.import-warnings": "Worth checking",
    "submit.import-error-title": "Could not read",
    "submit.import-error-empty": "Enter a GitHub repository URL first, e.g. https://github.com/owner/repo",
    "submit.import-error-invalid": "That does not look like a GitHub repository. The correct form is https://github.com/owner/repo",
    "submit.import-error-notfound": "Repository not found: check the spelling and make sure it is public.",
    "submit.import-error-ratelimit": "GitHub API rate limit reached (60 requests per hour without signing in). Try again later, or fill the form by hand.",
    "submit.import-error-network": "Request failed: {message}. GitHub may be unreachable from your network — retry later or fill the form by hand.",
    "submit.import-warn-release-failed": "Only the repository info could be read; releases were unavailable (rate limit or network issue), so add the downloads manually.",
    "submit.import-warn-no-release": "This repository has no release yet — the downloads section links to the releases page instead.",
    "submit.import-warn-no-asset": "The latest release has no downloadable files — the downloads section links to the release page instead.",
    "submit.import-warn-skipped": "Skipped {count} debug symbol / checksum files that are not installers.",
    "submit.import-warn-truncated": "Many assets found; only the first {count} were filled. Add the rest manually.",
    "submit.import-warn-prerelease": "The newest release {tag} is a pre-release (Beta / Alpha) — confirm it is appropriate before publishing.",
    "submit.import-warn-newer-prerelease": "A newer pre-release {tag} exists; tick \"Include pre-releases\" and read again if you want it.",
    "submit.import-warn-archived": "This repository has been archived by its owner and may no longer be updated.",
    "submit.import-warn-icon": "The icon currently points at the repository owner's avatar ({owner}); consider replacing it with the app's own icon.",
    "submit.import-warn-downloads-kept": "The downloads section already had content, so it was left alone. Tick \"Overwrite what I already typed\" and read again to use the release assets.",
    "submit.import-id-taken": "The app ID \"{id}\" already exists, so it was changed to \"{newId}\".",
    "submit.import-id-duplicate": "The app ID \"{id}\" already exists on this site — please pick another one.",
    "submit.import-latest-platform": "Latest GitHub release",
    "submit.import-latest-note": "Open the release page to download the latest installer",
    "submit.import-web": "Web page",
    "submit.import-notice-prerelease": "The version listed here is the official pre-release {tag} (Beta / Alpha) and may not be stable; download the latest stable build from GitHub Releases instead.",
    "submit.section-basic": "Basic info",
    "submit.section-extra": "Extra info",
    "submit.section-downloads": "Downloads",
    "submit.required": "Required",
    "submit.id": "App ID",
    "submit.id-placeholder": "e.g. notepad-plus-plus",
    "submit.id-desc": "Unique identifier, also part of the URL #/download/<id>. Use lowercase letters, digits and hyphens only",
    "submit.name": "App name",
    "submit.name-placeholder": "e.g. Notepad++",
    "submit.icon": "Icon URL",
    "submit.icon-placeholder": "https://... (optional, square preferred)",
    "submit.category": "Category",
    "submit.category-placeholder": "Select a category",
    "submit.tagline": "One-line summary",
    "submit.tagline-placeholder": "Shown on the home page card",
    "submit.description": "Full description",
    "submit.description-placeholder": "What it does and what makes it useful",
    "submit.version": "Version",
    "submit.version-placeholder": "e.g. 8.6.9",
    "submit.size": "Size",
    "submit.size-placeholder": "e.g. 25 MB",
    "submit.system": "System requirement",
    "submit.system-placeholder": "e.g. Windows 10/11 64-bit",
    "submit.website": "Official website",
    "submit.website-placeholder": "https://...",
    "submit.github": "GitHub repository",
    "submit.github-placeholder": "https://github.com/...",
    "submit.notice": "Update notice",
    "submit.notice-placeholder": "Optional, recommended for apps that update often",
    "submit.store": "Microsoft Store link",
    "submit.store-placeholder": "https://apps.microsoft.com/... (optional)",
    "submit.sort": "Sort order",
    "submit.sort-placeholder": "Defaults to 99; smaller numbers come first",
    "submit.download-index": "Download {index}",
    "submit.download-platform": "Platform / architecture",
    "submit.download-platform-placeholder": "e.g. Windows x64 installer",
    "submit.download-size": "Size",
    "submit.download-note": "Note",
    "submit.download-note-placeholder": "Optional",
    "submit.download-url": "Direct file URL",
    "submit.download-url-placeholder": "https://... .exe / .zip / .msi",
    "submit.download-add": "Add download",
    "submit.download-remove": "Remove",
    "submit.submit": "Submit",
    "submit.submitting": "Submitting…",
    "submit.error-required": "Please fill in all fields marked with *",
    "submit.error-network": "Network error: {message}",
    "submit.error-timeout": "Request timed out (no response in {seconds}s)",
    "submit.error-unexpected": "The submission service returned an unrecognised response",
    "submit.result-success-title": "Submitted",
    "submit.result-success": "Your submission is in the review queue and will go live once approved.",
    "submit.result-error-title": "Submission failed",
    "submit.result-error": "Please try again later, or open an issue in the repository.",
    "submit.fallback-title": "Submission service unreachable",
    "submit.fallback-desc": "The submission service could not be reached — this happens with regional limits on overseas traffic, or with unusual browser and network conditions. Nothing you typed is lost: retry later, or hand it in through GitHub.",
    "submit.fallback-retry": "Retry",
    "submit.fallback-download": "Download file",
    "submit.fallback-copy": "Copy content",
    "submit.fallback-copied": "Copied",
    "submit.fallback-github": "Submit on GitHub",
    "submit.fallback-github-hint": "Open the link and paste the JSON you just downloaded (keep the .json name under submissions/). You need to sign in to GitHub; without write access GitHub will guide you through forking and opening a pull request, and merged submissions enter the same review queue.",
    "submit.fallback-restore": "Restore last input",
    "submit.fallback-restore-title": "Input restored",
    "submit.fallback-restored": "Your previous input has been filled back in — hit Submit to retry.",
  "detail.system": "System requirements",
  "about.reward": "Reward the author",
  "about.reward-url": "https://ifdian.net/a/TinyNickCSHub",
  };
